version: "3.9"
services:
  router:
    image: traefik:2.6
    ports:
      - 80:80
      - 443:443
      - 8080:8080
      - 10053:10053/tcp
      - 10053:10053/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Map the base configuration into the container
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      # Map the dynamic configuration into the container
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # Map the certificats into the container
      - ./certs:/etc/certs:ro
    networks:
      - dev
  dns:
    image: jpillora/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    logging:
      options:
        max-size: 100m
    environment:
      - HTTP_USER=${DNS_USERNAME}
      - HTTP_PASS=${DNS_PASSWORD}
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.dns.rule=Host(`dns.${DOMAIN}`)
      - traefik.http.routers.dns.entrypoints=web,secureweb
      - traefik.http.routers.dns.tls=true
      - traefik.http.routers.dns.tls.domains.main=localdev.dring.tech
      - traefik.http.routers.dns.tls.domains.sans=*.localdev.dring.tech
      - traefik.http.services.dns.loadbalancer.server.port=8080
      - traefik.tcp.routers.dns.rule=HostSNI(`*`)
      - traefik.tcp.routers.dns.entrypoints=dnstcp
      - traefik.tcp.services.dns.loadbalancer.server.port=53
      - traefik.udp.routers.dns.entrypoints=dnsudp
      - traefik.udp.services.dns.loadbalancer.server.port=53
    networks:
      - dev

networks:
  dev:
    external: true