version: "3.9"
services:
  test-www:
    image: nginx
    volumes:
      - ./www:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.www.rule=Host(`test-www.${DOMAIN}`)
      - traefik.http.routers.www.entrypoints=web,secureweb
      - traefik.http.routers.www.tls=true
      - traefik.http.routers.www.tls.domains.main=localdev.dring.tech
      - traefik.http.routers.www.tls.domains.sans=*.localdev.dring.tech
    networks:
      - dev

networks:
  dev:
    external: true