http:
  routers:
    traefik:
      rule: "Host(`traefik.localdev.dring.tech`)"
      service: "api@internal"
      tls:
        domains:
          - main: "localdev.dring.tech"
            sans:
              - "*.localdev.dring.tech"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"