## traefik.yml

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    # defaultRule: "Host(`{{ trimPrefix `/` .Name }}.local.dring.tech`)"
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# API and dashboard configuration
api:
  insecure: true

#log:
#  level: DEBUG

entrypoints:
  dnstcp:
    address: ":10053/tcp"
  dnsudp:
    address: ":10053/udp"
  web:
    address: ":80/tcp"
#    http:
#      redirections:
#        entryPoint:
#          to: secureweb
#          scheme: https
  secureweb:
    address: ":443/tcp"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/certs/local-cert.pem"
        keyFile: "/etc/certs/local-key.pem"

# ping: {}
accessLog: {}